import { Inter } from "next/font/google";
import { SiteHeader } from "@/header/site-header";
import SiteFooter from "@/footer/site-footer";
import "./globals.css";
import Providers from "@/components/main/query-provider";
import AdmissionQueryButton from "@/components/main/AdmissionQueryButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <SiteHeader />
          <main>{children}</main>
          <AdmissionQueryButton />
          <SiteFooter />
        </Providers>
      </body>
    </html>
  );
}
